apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-storage"
  resources:
    requests:
      storage: 1Gi
